version: '3.1'

volumes:
  transactional_demo:

services:
  transactional_demo:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=transactional_demo
    volumes:
      - transactional_demo:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"