spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactional_demo
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
    contexts: dev